python3 src/main_pretrain.py \
    --mode pretrain \
    --image_mask_ratio 0.75 \
    --output-dir "$GCS_DATASET_DIR/CKPT" \
    --train-dataset-shards "$GCS_DATASET_DIR/imagenet-1k-wds/imagenet1k-train-{0000..1023}.tar" \
    --valid-dataset-shards "$GCS_DATASET_DIR/imagenet-1k-wds/imagenet1k-validation-{00..63}.tar" \
    --train-batch-size 4096 \
    --valid-batch-size 512 \
    --train-loader-workers 40 \
    --valid-loader-workers 10 \
    --random-crop rrc \
    --color-jitter 0.0 \
    --auto-augment "none" \
    --random-erasing 0.0 \
    --augment-repeats 1 \
    --test-crop-ratio 0.875 \
    --mixup 0.0 \
    --cutmix 0.0 \
    --layers 12 \
    --dim 768 \
    --heads 12 \
    --labels 0 \
    --patch-size 16 \
    --image-size 224 \
    --posemb sincos2d \
    --pooling cls \
    --dropout 0.0 \
    --droppath 0.0 \
    --dec-layers 8 \
    --dec-dim 512 \
    --dec-heads 16 \
    --dec-posemb sincos2d \
    --dec-dropout 0.0 \
    --dec-droppath 0.0 \
    --init-seed 0 \
    --mixup-seed 0 \
    --dropout-seed 0 \
    --noise-seed 0 \
    --shuffle-seed 0 \
    --optimizer adamw \
    --learning-rate 1.5e-4 \
    --weight-decay 0.05 \
    --adam-b1 0.9 \
    --adam-b2 0.95 \
    --adam-eps 1e-8 \
    --lr-decay 1.0 \
    --clip-grad 0.0 \
    --grad-accum 1 \
    --warmup-steps $((1281167 * 40 / 4096)) \
    --training-steps $((1281167 * 1600 / 4096)) \
    --log-interval 1000 \
    --eval-interval $((1281167 * 1 / 4096)) \
    --project MAE-JAX \
    --name $(basename $0 .sh) \
    --ipaddr $(curl -s ifconfig.me) \
    --hostname $(hostname)
